
//Lista wszystkich kategorii
GET http://localhost:8080/category


// Id konkretnej kategorii
###
GET http://localhost:8080/category/2


//dodawanie kategorii
###
POST http://localhost:8080/category
Accept: application/json
Content-Type: application/json

{
  "id": null,
  "parentId": 1.0,
  "name": "Ucheyt"
}

