
//Lista wszystkich kategorii
GET http://localhost:8081/category/all


// Id konkretnej kategorii
###
GET http://localhost:8081/category/1


//dodawanie kategorii
###
POST http://localhost:8081/category/add
Accept: application/json
Content-Type: application/json

{
  "id": null,
  "parentId": 1.0,
  "name": "Smartfony"
}

