
### lista wszystkich produktów
GET http://localhost:8080/product

### dodawnie produktu do listy
POST http://localhost:8080/product
Accept: application/json
Content-Type: application/json

{
  "id": null,
  "title": "Pralka",
  "description": "To jest dobra Pralka wspaniale Pierze",
  "price": 2000.0,
  "category": 20.0
}

### pobieranie do edycji konkretnego id produktu
GET http://localhost:8080/product/1

### edycja konktrentego id produktu
PUT http://localhost:8080/product/15
Accept: application/json
Content-Type: application/json

{
  "title": "Pralka",
  "description": "To jest dobra Pralka wspaniale Pierze",
  "price": 2000.0,
  "category": 20
}
###
DELETE http://localhost:8080/product/17
Accept: application/json
Content-Type: application/json


###  lista wszystkich produktów o danej kategorii
GET http://localhost:8080/product/category/100









